### ISSUE TITLE
illustrator tutorial

### ISSUE THREAD

**Issue by gsanikidze** [GeoLabCommunity/geolab-final-project--Atelier-alma-#1]

**Comment by Anichki** [comment]
google driv-ში ავტვირთე, თუ mov ფაილები ვერ გახსენით მომწერეთ დავაკონვერტირებ სხვა ფორმატში

**Comment by AlexiAmni** [comment]
ანი ლინკი?

**Comment by Anichki** [comment]
https://drive.google.com/open?id=0B2LVYYsw639PNnloQjFkMWZYMzQ
geolab-ის მეილით ყველას აქვს წვდომა

პირდაპირ დრაივში შეიძლება ნახვა, თუ კომპზე quicktimeplayer არ გაქვთ დაინსტალირებული
